version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: sppr-bd
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: sppr
    ports:
      - "54324:5432"
    volumes:
      - sppr:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d tools_bd" ]
      interval: 5s
      timeout: 3s
      retries: 10
    networks:
      - sppr

networks:
  sppr:
    driver: bridge

volumes:
  sppr: