version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: sppr-bd
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: sppr
    ports:
      - "54324:5432"
    volumes:
      - sppr:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d tools_bd" ]
      interval: 5s
      timeout: 3s
      retries: 10
    networks:
      - sppr

  sonar_db:
    image: postgres:13
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
      POSTGRES_DB: sonar
    volumes:
      - sonar_db:/var/lib/postgresql
      - sonar_db_data:/var/lib/postgresql/data

  sonarqube:
    image: sonarqube:lts-community
    depends_on:
      - sonar_db
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://sonar_db:5432/sonar
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: sonar
    ports:
      - "9003:9000"
    volumes:
      - sonarqube_conf:/opt/sonarqube/conf
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs
      - sonarqube_temp:/opt/sonarqube/temp

  minio:
    image: minio/minio:RELEASE.2023-12-23T07-19-11Z-cpuv1
    container_name: sppr-minio
    restart: unless-stopped
    environment:
      TZ: Europe/Moscow
      LANG: en_US.UTF-8
      MINIO_PROMETHEUS_AUTH_TYPE: "public"
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - sppr_minio_data:/data
    logging:
      driver: "json-file"
      options:
        max-size: "1000m"
    ports:
      - "9000:9000"
      - "9001:9001"
    networks:
      - sppr

  gitlab:
    image: 'gitlab/gitlab-ce:latest'
    hostname: 'gitlab.example.com'
    restart: always
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://gitlab.example.com'
        # Add any other gitlab.rb configuration here, each on its own line
        letsencrypt['enabled'] = false
    ports:
      - 80:80
      - 443:443
      - 22:22
    volumes:
      - gitlab_config:/etc/gitlab
      - gitlab-logs:/var/log/gitlab
      - gitlab-opt:/var/opt/gitlab

  rabbitmq_sppr:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq_sppr'
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbit_data:/var/lib/rabbitmq/
      - rabbit_log:/var/log/rabbitmq
    networks:
      - sppr
networks:
  sppr:
    driver: bridge

volumes:
  sppr:
  sppr_minio_data:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:
  sonarqube_conf:
  sonarqube_temp:
  sonar_db:
  sonar_db_data:
  gitlab_config:
  gitlab-logs:
  gitlab-opt:
  rabbit_data:
  rabbit_log: