version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: sppr-bd
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: sppr
    ports:
      - "54324:5432"
    volumes:
      - sppr:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d tools_bd" ]
      interval: 5s
      timeout: 3s
      retries: 10
    networks:
      - sppr


  minio:
    image: minio/minio:RELEASE.2023-12-23T07-19-11Z-cpuv1
    container_name: sppr-minio
    restart: unless-stopped
    environment:
      TZ: Europe/Moscow
      LANG: en_US.UTF-8
      MINIO_PROMETHEUS_AUTH_TYPE: "public"
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - sppr_minio_data:/data
    logging:
      driver: "json-file"
      options:
        max-size: "1000m"
    ports:
      - "9000:9000"
      - "9001:9001"
    networks:
      - sppr

networks:
  sppr:
    driver: bridge

volumes:
  sppr:
  sppr_minio_data: